import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import Providers from "@/components/layout/providers";
import { auth } from "@/lib/auth";
import { Toaster } from "@/components/ui/sonner";
import QueryProvider from "@/providers/query-provider";
import  NextTopLoader  from 'nextjs-toploader';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quản lý tuyển dụng - Recruitment",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log(session, 'session')
  return (
    <html lang="vi" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader 
          color="#2563eb"
          initialPosition={0.3}
          crawlSpeed={300}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease-in-out"
          speed={300}
          shadow="0 0 10px #2563eb,0 0 5px #2563eb"
          zIndex={9999}
        />
        <QueryProvider>
          <ThemeProvider>
            <Providers session={session}>
              {children}
              <Toaster />
            </Providers>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
